name: CI

on:
  pull_request:
  push:

jobs:
  eslint:
    name: ESLint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Run ESLint
        run: bun run eslint .

  prettier:
    name: Prettier Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Run Prettier
        run: bun run prettier --check .

  tsc:
    name: TypeScript Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Run TypeScript Compiler
        run: bun run tsc --noEmit

  build-macos:
    name: Build CLI (macOS)
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build CLI for x64
        run: bun build src/cli/cli.ts --target bun-darwin-x64 --outdir dist/macos/x64

      - name: Build CLI for arm64
        run: bun build src/cli/cli.ts --target bun-darwin-arm64 --outdir dist/macos/arm64

      - name: Combine binaries using lipo
        run: |
          lipo -create -output dist/macos/universal/cli dist/macos/x64/cli dist/macos/arm64/cli

  build-windows:
    name: Build CLI (Windows)
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build CLI for x64
        run: bun build src/cli/cli.ts --target bun-windows-x64 --outdir dist/windows/x64

      - name: Build CLI for x64 (baseline)
        run: bun build src/cli/cli.ts --target bun-windows-x64-baseline --outdir dist/windows/x64-baseline

      - name: Use Resource Hacker
        run: |
          ResourceHacker.exe -open dist/windows/x64/cli.exe -save dist/windows/x64/cli_modified.exe -action addoverwrite -res resource.res
          ResourceHacker.exe -open dist/windows/x64-baseline/cli.exe -save dist/windows/x64-baseline/cli_modified.exe -action addoverwrite -res resource.res

  build-linux:
    name: Build CLI (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build CLI for x64
        run: bun build src/cli/cli.ts --target bun-linux-x64 --outdir dist/linux/x64

      - name: Build CLI for x64 (baseline)
        run: bun build src/cli/cli.ts --target bun-linux-x64-baseline --outdir dist/linux/x64-baseline

      - name: Build CLI for arm64
        run: bun build src/cli/cli.ts --target bun-linux-arm64 --outdir dist/linux/arm64
