name: CI

on:
  pull_request:
  push:

jobs:
  eslint:
    name: ESLint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Run ESLint
        run: bun run eslint .

  prettier:
    name: Prettier Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Run Prettier
        run: bun run prettier --check .

  tsc:
    name: TypeScript Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Run TypeScript Compiler
        run: bun run tsc --noEmit

  build-macos:
    name: Build CLI (macOS)
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build CLI for x64
        run: bun build:cli --target=bun-darwin-x64 --outfile=dist/cli/macos/cli_macos_x64

      - name: Build CLI for arm64
        run: bun build:cli --target=bun-darwin-arm64 --outfile=dist/cli/macos/cli_macos_arm64

      - name: Combine binaries using lipo
        run: |
          lipo -create -output dist/cli/macos/cli_macos dist/cli/macos/cli_macos_arm64 dist/cli/macos/cli_macos_x64

  build-windows:
    name: Build CLI (Windows)
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build CLI for x64
        run: bun build:cli --target=bun-windows-x64 --outfile=dist/cli/windows/cli_windows_x64.exe

      - name: Build CLI for x64 (baseline)
        run: BUN_RUNTIME_TRANSPILER_CACHE_PATH=0 bun build:cli --target=bun-windows-x64-baseline --outfile=dist/cli/windows/cli_windows_x64_baseline.exe

      - name: Use Resource Hacker
        run: |
          ResourceHacker.exe -open dist/cli/windows/cli_windows_x64.exe -save dist/cli/windows/cli_windows_x64.exe -action addoverwrite -res resource.res
          ResourceHacker.exe -open dist/cli/windows/cli_windows_x64_baseline.exe -save dist/cli/windows/cli_windows_x64_baseline.exe -action addoverwrite -res resource.res

  build-linux:
    name: Build CLI (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build CLI for x64
        run: bun build:cli --target=bun-linux-x64 --outfile=dist/cli/linux/cli_linux_x64

      - name: Build CLI for x64 (baseline)
        run: bun build:cli --target=bun-linux-x64-baseline --outfile=dist/cli/linux/cli_linux_x64_baseline

      - name: Build CLI for arm64
        run: bun build:cli --target=bun-linux-arm64 --outfile=dist/cli/linux/cli_linux_arm64
